fullnameOverride: sealed-secrets
image:
  registry: ghcr.io
  repository: bitnami/sealed-secrets-controller
  tag: 0.40.0
resources:
  requests: {cpu: 25m, memory: 64Mi}
  limits: {cpu: 200m, memory: 128Mi}
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - {key: intentlatch.io/role, operator: NotIn, values: [ollama]}
